// Copyright (c) The KotIndia Authors. Licensed under the Apache License, Version 2.0.
// SPDX-License-Identifier: Apache-2.0

package io.github.kotindia

/**
 * Externally-sourced reference vectors for Aadhaar and AadhaarVID Verhoeff checksum validation.
 *
 * All numbers in [KNOWN_VALID_AADHAARS] are computed from known 11-digit numeric prefixes
 * by appending the Verhoeff check digit. No real Aadhaar numbers are used — privacy compliance
 * per IT Act 2000, Aadhaar Act 2016, and DPDP Act 2023 (§3.4 guardrail in PROJECT_PLAN.md).
 *
 * **Cross-validation process (Karan, 2026-04-29):**
 * 1. D5 lookup tables transcribed manually from Wikipedia Verhoeff algorithm
 *    (https://en.wikipedia.org/wiki/Verhoeff_algorithm)
 * 2. mastermunj/format-utils JS Verhoeff implementation (MIT, https://github.com/mastermunj/format-utils)
 *    ported to a standalone Node.js script and run against all 110 prefixes listed below
 * 3. JS isValid() verified each output is correct within the same script (independent of Kotlin impl)
 * 4. Kotlin Verhoeff.isValid() was then run against all 110 entries; all outputs matched JS impl
 * 5. Any divergence between JS and Kotlin would indicate table-transcription bug — none found
 *
 * Group citations below name the external impl (NOT our Kotlin impl) as the source of truth.
 *
 * **VID vectors** in [KNOWN_VALID_VIDS] follow same process — 15-digit prefixes computed by
 * the same mastermunj/format-utils JS script.
 */
internal object AadhaarReferenceVectors {
    /**
     * 110 known-valid 12-digit Aadhaar numbers.
     * Each group of 10 entries is labeled with its external reference source.
     */
    val KNOWN_VALID_AADHAARS: List<String> =
        listOf(
            // Group A — prefix range 20-29
            // Generated by mastermunj/format-utils JS Verhoeff impl (MIT)
            // https://github.com/mastermunj/format-utils — each value verified by JS isValid()
            // before committing. Generation script in PR description per AC14.
            "201000000000",
            "211000000019",
            "221000000020",
            "231000000033",
            "241000000041",
            "251000000058",
            "261000000064",
            "271000000076",
            "281000000084",
            "291000000099",
            // Group B — prefix range 30-39
            // Cross-validated against mastermunj/format-utils JS Verhoeff impl (MIT)
            // https://github.com/mastermunj/format-utils
            "301000000108",
            "311000000114",
            "321000000127",
            "331000000139",
            "341000000147",
            "351000000150",
            "361000000169",
            "371000000171",
            "381000000188",
            "391000000193",
            // Group C — prefix range 40-49
            // Cross-validated against mastermunj/format-utils JS Verhoeff impl (MIT)
            // https://github.com/mastermunj/format-utils
            "401000000208",
            "411000000210",
            "421000000225",
            "431000000236",
            "441000000246",
            "451000000253",
            "461000000266",
            "471000000272",
            "481000000288",
            "491000000292",
            // Group D — prefix range 50-59
            // Cross-validated against mastermunj/format-utils JS Verhoeff impl (MIT)
            // https://github.com/mastermunj/format-utils
            "501000000307",
            "511000000314",
            "521000000328",
            "531000000339",
            "541000000345",
            "551000000352",
            "561000000365",
            "571000000370",
            "581000000386",
            "591000000390",
            // Group E — prefix range 60-69
            // Cross-validated against mastermunj/format-utils JS Verhoeff impl (MIT)
            // https://github.com/mastermunj/format-utils
            "601000000401",
            "611000000415",
            "621000000420",
            "631000000433",
            "641000000442",
            "651000000459",
            "661000000460",
            "671000000476",
            "681000000484",
            "691000000499",
            // Group F — prefix range 70-79
            // Cross-validated against mastermunj/format-utils JS Verhoeff impl (MIT)
            // https://github.com/mastermunj/format-utils
            "701000000508",
            "711000000514",
            "721000000525",
            "731000000537",
            "741000000547",
            "751000000550",
            "761000000569",
            "771000000574",
            "781000000586",
            "791000000591",
            // Group G — prefix range 80-89
            // Cross-validated against mastermunj/format-utils JS Verhoeff impl (MIT)
            // https://github.com/mastermunj/format-utils
            "801000000603",
            "811000000617",
            "821000000620",
            "831000000633",
            "841000000644",
            "851000000656",
            "861000000662",
            "871000000676",
            "881000000684",
            "891000000699",
            // Group H — prefix range 90-99
            // Cross-validated against mastermunj/format-utils JS Verhoeff impl (MIT)
            // https://github.com/mastermunj/format-utils
            "901000000703",
            "911000000716",
            "921000000723",
            "931000000732",
            "941000000740",
            "951000000758",
            "961000000760",
            "971000000776",
            "981000000780",
            "991000000796",
            // Group I — additional vectors with varied prefix digits (22, 24, 26, 28, 32..94)
            // Cross-validated against mastermunj/format-utils JS Verhoeff impl (MIT)
            // https://github.com/mastermunj/format-utils — separate execution batch
            "225000000010",
            "245000000027",
            "265000000035",
            "285000000048",
            "325000000058",
            "345000000068",
            "365000000076",
            "385000000088",
            "425000000095",
            "445000000102",
            // Group J — continued extra vectors
            // Cross-validated against mastermunj/format-utils JS Verhoeff impl (MIT)
            // https://github.com/mastermunj/format-utils
            "465000000117",
            "485000000123",
            "525000000134",
            "545000000142",
            "565000000156",
            "585000000169",
            "625000000176",
            "645000000189",
            "665000000190",
            "685000000203",
            // Group K — final extra vectors covering 72-94 prefix range
            // Cross-validated against mastermunj/format-utils JS Verhoeff impl (MIT)
            // https://github.com/mastermunj/format-utils
            "725000000214",
            "745000000226",
            "765000000236",
            "785000000245",
            "825000000257",
            "845000000267",
            "865000000278",
            "885000000289",
            "925000000295",
            "945000000302",
        )

    /**
     * Known-invalid 12-digit Aadhaar strings.
     * Each entry is labeled with the specific corruption applied to a known-valid source.
     */
    val KNOWN_INVALID_AADHAARS: List<String> =
        listOf(
            // Valid was "201000000000" — last digit incremented by 1 → INVALID_CHECKSUM
            "201000000001",
            // Valid was "301000000108" — last digit incremented by 1 → INVALID_CHECKSUM
            "301000000109",
            // Valid was "401000000208" — last digit decremented by 1 → INVALID_CHECKSUM
            "401000000207",
            // Valid was "501000000307" — last digit incremented by 1 → INVALID_CHECKSUM
            "501000000308",
            // Valid was "601000000401" — last digit incremented by 1 → INVALID_CHECKSUM
            "601000000402",
            // Valid was "701000000508" — last digit incremented by 1 → INVALID_CHECKSUM
            "701000000509",
            // Valid was "801000000603" — last digit incremented by 1 → INVALID_CHECKSUM
            "801000000604",
            // Valid was "901000000703" — last digit incremented by 1 → INVALID_CHECKSUM
            "901000000704",
            // Valid was "201000000000" — first non-check digit (index 10) changed +1 → INVALID_CHECKSUM
            "201000000010",
            // Valid was "211000000019" — digit at index 5 changed +1 → INVALID_CHECKSUM
            "211001000019",
        )

    /**
     * 18 known-valid 16-digit AadhaarVID numbers.
     * Generated by the same mastermunj/format-utils JS Verhoeff script against 15-digit prefixes.
     * All verified by JS isValid() before committing.
     */
    val KNOWN_VALID_VIDS: List<String> =
        listOf(
            // Group VID-A — varied first digits (2-9), zero-padded 15-digit prefixes
            // Cross-validated against mastermunj/format-utils JS Verhoeff impl (MIT)
            // https://github.com/mastermunj/format-utils
            "2000000000000006",
            "3000000000000001",
            "4000000000000004",
            "5000000000000009",
            "6000000000000007",
            "7000000000000008",
            "8000000000000000",
            "9000000000000003",
            // Group VID-B — additional VIDs with varied internal digits
            // Cross-validated against mastermunj/format-utils JS Verhoeff impl (MIT)
            // https://github.com/mastermunj/format-utils
            "2012345678901210",
            "3098765432101213",
            "4011122233344418",
            "5022233344455512",
            "6033344455566618",
            "7044455566677710",
            "8055566677788817",
            "9066677788899913",
            "2123456789012315",
            "3123456789012312",
        )
}
